home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    #トップページ
    path('', views.index, name='index'),

    #サービスについて
    path('serve', views.service, name = 'service'),
    
    path('contact', views.contact, name = 'contact'),
    
]

list/urls.py
from django.urls import path
from list import views
from django.conf.urls.static import static # 追加
from django.conf import settings # 追加

app_name = 'list'
urlpatterns = [
    # 一覧
    path('list/', views.list, name='list'),
    path('detail/', views.detail, name='detail'),
    path('delete/', views.delete, name = 'delete'),
    path('<int:shop_id>/<int:comment_id>', views.delete_d, name = 'delete_d'),
    path('<int:shop_id>/', views.inf, name = 'inf'),
    ]
if settings.DEBUG:
    urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    # path('', views.home, name='home'),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from list import views
from django.conf.urls.static import static # 追加
from django.conf import settings # 追加

urlpatterns = [
    # path('', views.home, name='home'),
    path('', include('home.urls')),
    path('', include('list.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

list/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone

#from list import views #追加モジュール_電話番号、郵便番号に使う


class Shop(models.Model):
    """店舗名"""
    name = models.CharField('店舗名', max_length=255)
    """概要"""
    views = models.TextField('説明')
    """郵便番号"""
    #postal_code_regex 郵便番号は「1234567」の形式で入力する必要があります。最大7桁まで使用できます。
    postal_code_regex = RegexValidator(regex=r'^[0-9]{7}$', message = ("Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed."))
    pos_code = models.CharField(validators=[postal_code_regex], max_length=7, verbose_name='郵便番号')
    """住所"""
    #場所によっては長くなるため
    address = models.CharField('住所', max_length=255)
    """電話番号"""
    #tel_number_regex 電話番号は「09012345678」の形式で入力する必要があります。最大15桁まで使用できます。
    tel_number_regex = RegexValidator(regex=r'^[0-9]{10,11}$', message = ("Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed."))
    tel_num = models.CharField(validators=[tel_number_regex], max_length=15, verbose_name='電話番号')
    """公式サイトURL"""
    #場所によっては長くなるため
    site_url = models.CharField('site_URL', max_length=255)
    """画像URL"""
    img_url =models.ImageField('img_URL', upload_to = 'images', blank = True, null = True)

"""コロナ対策"""
class Check(models.Model):
    """店のコロナ対策"""
    check_23 = models.BooleanField('check_23', default=False, null=True)
    check_33 = models.BooleanField('check_33', default=False, null=True)
    check_34 = models.BooleanField('check_34', default=False, null=True)
    check_35 = models.BooleanField('check_35', default=False, null=True)
    check_36 = models.BooleanField('check_36', default=False, null=True)
    check_41 = models.BooleanField('check_41', default=False, null=True)
    """お客様へのお願い"""
    check_2 = models.BooleanField('check_2', default=False, null=True)
    check_3 = models.BooleanField('check_3', default=False, null=True)
    check_4 = models.BooleanField('check_4', default=False, null=True)
    check_10 = models.BooleanField('check_10', default=False, null=True)
    check_12 = models.BooleanField('check_12', default=False, null=True)
    check_15 = models.BooleanField('check_15', default=False, null=True)
    check_22 = models.BooleanField('check_22', default=False, null=True)
    check_28 = models.BooleanField('check_28', default=False, null=True)
    check_32 = models.BooleanField('check_32', default=False, null=True)

    """shopとの関係"""
    shop = models.OneToOneField(Shop, related_name="shop_check", on_delete=models.CASCADE, null=True)

class Comment(models.Model):
    """タイトル"""
    title = models.CharField('タイトル', max_length=255)
    """名前"""
    name = models.CharField('名前', max_length=255)
    """コメント"""
    comment = models.TextField('コメント')
    """作成時間"""
    regist_date = models.DateTimeField(default=timezone.now)
    """ショップ"""
    Shop = models.ForeignKey(Shop, on_delete=models.CASCADE)


    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from list.models import Shop


def index(request):
    context = {
        'shops': Shop.objects.all()
    }
    return render(request,'home/index.html', context)

def service(request):
    return render(request, 'home/service.html')

def contact(request):
    return render(request, 'home/contact.html')

list/views.py
from tabnanny import check
from unicodedata import name
from xml.etree.ElementTree import Comment
from django.http.response import Http404
from django.shortcuts import render, redirect
from django.http import HttpResponse
from list.models import Shop
from list.models import Check
from list.models import Comment
from mysite.settings import MEDIA_ROOT
import os
from pathlib import Path
import urllib
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect

@csrf_protect

# 登録、編集
def detail(request):
    if request.method == 'POST':
        shop = Shop(
            name=request.POST['name'],
            pos_code = request.POST['pos_code'],
            address = request.POST['address'],
            tel_num = request.POST['tel_num'],
            site_url = request.POST['URL'],
            img_url = request.FILES['img'],
            views = request.POST['views']
        )
        shop.save()
        check = Check(
            check_23 = request.POST['check_23'],
            check_33 = request.POST['check_33'],
            check_34 = request.POST['check_34'],
            check_35 = request.POST['check_35'],
            check_36 = request.POST['check_36'],
            check_41 = request.POST['check_41'],
            check_2 = request.POST['check_2'],
            check_3 = request.POST['check_3'],
            check_4 = request.POST['check_4'],
            check_10 = request.POST['check_10'],
            check_12 = request.POST['check_12'],
            check_15 = request.POST['check_15'],
            check_22 = request.POST['check_22'],
            check_28 = request.POST['check_28'],
            check_32  = request.POST['check_32'],
            shop = shop
        )
        check.save()

        return redirect('../list')


    return render(request, 'list/detail.html')

#一覧
def list(request):
    q_word = request.GET.get('query')

    if q_word:
        context = {
            'shops': Shop.objects.filter(Q(name__icontains=q_word) | Q(address__icontains=q_word)),
            }
    else:
        context = {
            'shops': Shop.objects.all(),
            }
    
    return render(request, 'list/list.html', context)

#詳細画面
def inf(request, shop_id):
    try:
        shop = Shop.objects.get(pk=shop_id)
    except Shop.DoesNotExist:
        raise Http404("見つからないよ")
    context = {
        'shop' : shop
    }
    if request.method == 'POST':
        comment = Comment(
            title=request.POST['title'],
            name=request.POST['name'],
            comment=request.POST['comment'],
            Shop = shop
        )
        comment.save()
    return render(request, 'list/information.html', context)

#新規と編集
def edit(request, id=None):
    return HttpResponse("編集")

#削除_コメント
def delete_d(request, shop_id, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
    except Comment.DoesNotExist:
        raise Http404("Comment does not exist")
    comment.delete()
    url = '../' + str(shop_id)
    return redirect(url)

#削除_store
def delete(request):
    image_path = []
    try:
        shop = Shop.objects.all()
        check = Check.objects.all()
        for a in shop:
            os.remove(os.path.join(MEDIA_ROOT.__str__(), a.img_url.name))
    except Shop.DoesNotExist:
        raise Http404("Shop does not exist")
    shop.delete()
    check.delete()
    return redirect('../list')

home/templates/home/contact.html
{% extends "home/layout.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

<div class="box">
  <div class="pos">
    <ul>
      <li>当サイト制作者：</li>
      <li>連絡先：</li>
    </ul>
  </div>
  <div class="person">
    <ul>
      <li>NAME</li>
      <li>TEL＿NUM</li>
    </ul>
  </div>
</div>


{% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends "home/layout.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <div class="search">
    <form action="{% url 'list:list' %}" method="get">
        <div class="search_c">
        <input name="query" value="{{ request.GET.query }}" type="text" id="search-text">
        <button type="submit" id='search-buttun'>検索する</button>
        </div>
    </form>
    </div>
    <div class="area_m">
    <nav class="area">
    <h2 class="title">エリア検索</h2>
    <ul>
        <li>北海道</li>
        <li>東北</li>
        <li>関東</li>
        <li>中部・近畿</li>
        <li>四国</li>
        <li>九州</li>
        <li>沖縄</li>
    </ul>
    </nav>
    </div>
    <div class="item">
      <div class="item_image">
        <img class="img" src = "media/index/image10_3.png" width="300px" height = "auto">
      </div>
      <div class="item-text">
        <h2>コロナ禍で不安になっているあなたに</h2>
        <p>
          緊急事態宣言によって外出が制限されてしまいました。<br>
          宣言が解除された今でも<br>
          外出に不安を感じたりしませんか？<br>
          このサイトで気になるお店や施設を見つけてお出かけしましょう
        </p>
      </div>
    </div>
    <div class="item">
      <div class="item_image">
        <img class="img" src = "media/index/portal_top.jpeg" width="300px" height = "auto">
      </div>
      <div class="item-text">
        <h2>コロナ禍で不安になっているお店の方へ</h2>
        <p>
          コロナ禍の影響でお仕事に影響が出たでしょう<br>
          このサイトを利用してぜひお店のアピールをしてください<br>
          他のお店の情報からあなたのお店で<br>
          活かせるものがあるかもしれません
        </p>
      </div>
    </div>
  </div>

    <div class="tag">
        <h2>タグ検索</h2>
        <ul>
            <li>
              <form method="get" action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" value="check_23" src='media/all/023.png' width="auto" height="75px">
              </form>
            </li>
            <li>
              <form method="get" action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" value="check_33" src='media/all/033.png' width="auto" height="75px">
              </form>
            </li>
            <li>
              <form method="get"action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" hello="check_34" src='media/all/034.png' width="auto" height="75px">
              </form>
            </li>
            <li>
              <form method="get" action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" value="check_34" src='media/all/035.png' width="auto" height="75px">
              </form>
            </li>
            <li>
              <form method="get" action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" value="check_36" src='media/all/036.png' width="auto" height="75px">
              </form>
            </li>
            <li>
              <form method="get" action="{% url 'list:list' %}">
                  {% csrf_token %}
                  <input type="image" name="check" value="check_41" src='media/all/041.png' width="auto" height="75px">
              </form>
            </li>

        </ul>
    </div>

{% endblock %}
</body>
</html>

home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">

</head>
<body>

    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">
    <nav>
        <ul class="gnav-navi-1">
            <li><a href="{% url 'home:index' %}">TOP<br>トップ</a></li>
            <li><a href="{% url 'home:service' %}">SERVICE<br>サービスについて</a></li>
            <li><a href="{% url 'list:list' %}">LIST<br>お店一覧</a></li>
            <li><a href="{% url 'home:contact' %}">CONTACT<br>お問合せ</a></li>
            <li><a href="{% url 'list:detail' %}">REGISTER<br>登録</a></li>
        </ul>
    </nav>

    {% block content %}

    {% endblock %}

</body>
</html>

home/templates/home/service.html
{% extends "home/layout.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

<h1>サービス</h1>

<div class="contents">
  <div class="title">
    <h2>１．投稿されたお店の閲覧</h2>
    <img src="media/index/detail.png" width="400px" height="auto">
  </div>
  <div class="text">
    <h3>
      本サイトに登録されたお店や施設の閲覧ができます。<br>
      名前や住所などはもちろんのこと、<br>
      「お店のコロナ対策」や<br>「お店からお客様へのお願い」も掲載されています。
    </h3>
  </div>
</div>

<div class="contents">
  <div class="title">
    <h2>２．お店の登録</h2>
    <img src="media/index/register.png" width="400px" height="auto">
  </div>
  <h3 class="text">
    本サイトにお店や施設の情報を登録することができます。<br>
    基本情報に加えて「お店のコロナ対策」や<br>「お店からお客様へのお願い」を登録することで<br>
    お客様へコロナ対策をアピールすることができます。
  </h3>
</div>

<div class="contents">
  <div class="title">
    <h2>３．コメントの登録</h2>
    <img src="media/index/comment.png" width="400px" height="auto">
  </div>
  <h3 class="text">
    本サイトに登録されているお店や施設に<br>コメントを登録することができます。<br>
    感想や疑問をコメントして<br>ユーザー間で情報を共有することができます。<br>
    ※誹謗中傷や根拠のない批判や全否定的なコメントは<br>しないようご協力お願いします。
  </h3>
</div>

{% endblock %}
</body>
</html>

list/templates/list/detail.html
{% extends "home/layout.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>

{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
    <h1>登録画面</h1>
    <form method='post' class='form' enctype="multipart/form-data">
      {% csrf_token %}

    <table>
    <tr>
      <th>店名</th>
      <td>
        <input class="titleInput" name="name" type="text" placeholder="お店の名前" required>
      </td>
    </tr>

    <tr>
      <th>郵便番号</th>
      <td>
      <input class="titleInput" name="pos_code" type="text" pattern="[0-9]{3}-[0-9]{4}" placeholder="ex.)111-0000" required>
      </td>
    </tr>

    <tr>
      <th>住所</th>
      <td>
      <input class="titleInput" name="address" type="text" placeholder="OO県 区市町村 住所・建物名"required>
      </td>
    </tr>

    <tr>
      <th>電話番号</th>
      <td>
      <input class="titleInput" name="tel_num" type="tel" pattern="\d{2,4}-\d{2,4}-\d{3,4}" placeholder="ex.)090-1111-2222">
      </td>
    </tr>

    <tr>
      <th>公式サイトなどのURL</th>
      <td>
      <input class="titleInput" name="URL" type="url" placeholder="URL">
      </td>
    </tr>

    <tr>
      <th>概要<br>アピールポイント</th>
      <td>
      <textarea name="views"></textarea>
      </td>
    </tr>

    <div class="boxes">
    <tr>
      <th>コロナ対策</th>
      <td>
        <input type="hidden" name="check_23" value="0">
        <input class="check" type="checkbox" name="check_23" id="box_1" value="1"><label for="box_1">座席の間隔を開けています</label>
        <input type="hidden" name="check_33" value="0">
        <input class="check" type="checkbox" name="check_33" id="box_2" value="1"><label for="box_2">換気の徹底</label>
        <input type="hidden" name="check_34" value="0">
        <input class="check" type="checkbox" name="check_34" id="box_3" value="1"><label for="box_3">従業員のマスク着用・手洗いの徹底</label>
        <input type="hidden" name="check_35" value="0">
        <input class="check" type="checkbox" name="check_35" id="box_4" value="1"><label for="box_4">従業員の健康管理の徹底</label>
        <input type="hidden" name="check_36" value="0">
        <input class="check" type="checkbox" name="check_36" id="box_5" value="1"><label for="box_5">店内の衛生管理の徹底</label>
        <input type="hidden" name="check_41" value="0">
        <input class="check" type="checkbox" name="check_41" id="box_6" value="1"><label for="box_6">食品の衛生管理</label>
      </td>
    </tr>

    <tr>
      <th>コロナ対策<br>お客様へのお願い</th>
      <td>
        <input type="hidden" name="check_2" value="0">
        <input class="check" type="checkbox" name="check_2" id="box_7" value="1"><label for="box_7">ソーシャルディスタンスのお願い</label>
        <input type="hidden" name="check_3" value="0">
        <input class="check" type="checkbox" name="check_3" id="box_8" value="1"><label for="box_8">マスク着用のお願い</label>
        <input type="hidden" name="check_4" value="0">
        <input class="check" type="checkbox" name="check_4" id="box_9" value="1"><label for="box_9">入店は少人数で</label>
        <input type="hidden" name="check_10" value="0">
        <input class="check" type="checkbox" name="check_10" id="box_10" value="1"><label for="box_10">大声を控えて</label>
        <input type="hidden" name="check_12" value="0">
        <input class="check" type="checkbox" name="check_12" id="box_11" value="1"><label for="box_11">消毒のお願い</label>
        <input type="hidden" name="check_15" value="0">
        <input class="check" type="checkbox" name="check_15" id="box_12" value="1"><label for="box_12">並ぶ時は間隔を空けて</label>
        <input type="hidden" name="check_22" value="0">
        <input class="check" type="checkbox" name="check_22" id="box_13" value="1"><label for="box_13">会話を控えて</label>
        <input type="hidden" name="check_28" value="0">
        <input class="check" type="checkbox" name="check_28" id="box_14" value="1"><label for="box_14">マスクをつけて会話</label>
        <input type="hidden" name="check_32" value="0">
        <input class="check" type="checkbox" name="check_32" id="box_15" value="1"><label for="box_15">入退時に消毒のお願い</label>
      </td>
    </tr>
    </div>

    <tr>
      <th>画像ファイル</th>
      <td>
      <input id="imgInput" type="file" name="img" required>
      </td>
    </tr>
    </table>

    <div>
      <button type="submit" class='register'>送信</button>
    </div>
  </form>


  <button class="back"><a href="{% url 'list:list' %}">一覧へ戻る</a></button>
  {% endblock %}
</body>
</html>

list/templates/list/information.html
{% extends "home/layout.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>
<title>{{shop.name}}の情報</title>

<link rel="stylesheet" type="text/css" href="{% static 'css/information.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}">


<div class="container">

    <div class="content">
      <div>
        <div class="containt_img">
          <img src="/media/{{ shop.img_url }}" width="auto" height="200px"/>
        </div>

        <ul class="main">
          <li>店名：{{ shop.name }}</li>
          <li>住所：{{ shop.pos_code }} {{ shop.address }}</li>
        </ul>

        <ul class="sab">
          <li>電話番号：{{ shop.tel_num }}</li>
          <li>公式URL：<a href="{{ shop.site_url }}">{{ shop.site_url }}</a></li>
        </ul>
      </div>

        <ul class="measures">
        <p>お店が実施している対策</p>
        <li>
            {% if shop.shop_check.check_23 == 1 %}
            <img src="/media/all/023.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_33 == 1 %}
            <img src="/media/all/033.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_34 == 1 %}
            <img src="/media/all/034.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_35 == 1 %}
            <img src="/media/all/035.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_36 == 1 %}
            <img src="/media/all/036.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_41 == 1 %}
            <img src="/media/all/041.png" width="auto" height="100px">
            {% endif %}
        </li>
        <p>お店からお客様へのお願い</p>
        <li>
            {% if shop.shop_check.check_2 == 1 %}
            <img src="/media/all/002.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_3 == 1 %}
            <img src="/media/all/003.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_4 == 1 %}
            <img src="/media/all/004.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_10 == 1 %}
            <img src="/media/all/010.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_12 == 1 %}
            <img src="/media/all/012.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_15 == 1 %}
            <img src="/media/all/015.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_22 == 1 %}
            <img src="/media/all/022.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_28 == 1 %}
            <img src="/media/all/028.png" width="auto" height="100px">
            {% endif %}
        </li>
        <li>
            {% if shop.shop_check.check_32 == 1 %}
            <img src="/media/all/032.png" width="auto" height="100px">
            {% endif %}
        </li>
        </ul>
      <div>
          <p id="right_bottom">登録ID：{{ shop.id }}</p>
      </div>
    </div>

    <div class="overviews">
        <h1>お店の概要</h1>
        <p>{{shop.views}}</p>
    </div>
</div>
<div class="comments">
    <h2>コメント欄</h2>
    {% if shop.comment_set.all %}
    {% for comment in shop.comment_set.all %}
    <div class="comment">
        <div>
            <ul>
                <li class="title_name">
                    <h2>{{comment.title}}</h2>
                </li>
                <li class="title_name">
                    <p>{{comment.name}}</p>
                    
                </li>
            </ul>
            <div class="comment_m">
                <p>{{comment.comment}}</p>
            </div>
            <div class="comment_d">
                <button class="register_d"><a href="{% url 'list:delete_d' shop.id comment.id %}">コメント削除</a></button>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <ul><li>データがないよ</li></ul>
    {% endif %}
</div>

<form method='post' class='form' enctype="multipart/form-data">
    {% csrf_token %}
<div class="Input">
    <ul>
        <li class="wide">
            <input class="titleInput" type="text" name="title" placeholder="コメントタイトル" required>
        </li><!--余白削除用
        --><li class="wide">
            <input class="titleInput" type="text" name="name" placeholder="お名前" required>
        </li>
        <li>
            <textarea class="commentInput" type="text" name="comment"  rows="4" cols="40" placeholder="コメント内容" required></textarea>
        </li>
    </ul>
    <div>
        <button type="submit" class='register'>コメント送信</button>
    </div>
</div>
</form>
<button class="register" id="right_bottom"><a href="{% url 'list:list' %}">一覧へ戻る</a></button>
{% endblock %}
</body>
</html>

list/templates/list/list.html
{% extends "home/layout.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
</head>
<body>

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
  <form action="{% url 'list:detail' %}" method="post"></form>
    <div class="container">
      <h1>一覧表示</h1>
      {% if shops %}
      {% for shop in shops %}
      <div class="content">
        <div>
          <div class="containt_img">
            <img src="/media/{{ shop.img_url }}" width="auto" height="200px"/>
          </div>

          <ul class="main">
            <li>店名：<a href="{% url 'list:inf' shop.id %}">{{ shop.name }}</a></li>
            <li>住所：{{ shop.pos_code }} {{ shop.address }}</li>
          </ul>

          <ul class="sab">
            <li>電話番号：{{ shop.tel_num }}</li>
            <li>公式URL：<a href="{{ shop.site_url }}">{{ shop.site_url }}</a></li>
          </ul>
        </div>

        <ul class="measures">
          <p>お店が実施している対策</p>
          <li>
              {% if shop.shop_check.check_23 == 1 %}
              <img src="/media/all/023.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_33 == 1 %}
              <img src="/media/all/033.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_34 == 1 %}
              <img src="/media/all/034.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_35 == 1 %}
              <img src="/media/all/035.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_36 == 1 %}
              <img src="/media/all/036.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_41 == 1 %}
              <img src="/media/all/041.png" width="auto" height="100px">
              {% endif %}
          </li>
          <p>お店からお客様へのお願い</p>
          <li>
              {% if shop.shop_check.check_2 == 1 %}
              <img src="/media/all/002.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_3 == 1 %}
              <img src="/media/all/003.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_4 == 1 %}
              <img src="/media/all/004.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_10 == 1 %}
              <img src="/media/all/010.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_12 == 1 %}
              <img src="/media/all/012.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_15 == 1 %}
              <img src="/media/all/015.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_22 == 1 %}
              <img src="/media/all/022.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_28 == 1 %}
              <img src="/media/all/028.png" width="auto" height="100px">
              {% endif %}
          </li>
          <li>
              {% if shop.shop_check.check_32 == 1 %}
              <img src="/media/all/032.png" width="auto" height="100px">
              {% endif %}
          </li>
        </ul>

        <div>
          <p class="right_bottom">登録ID：{{ shop.id }}</p>
        </div>
      </div>
      {% endfor %}

      {% else %}
      <p>データがないよ</p>
      {% endif %}

    </div>

    <a href="{% url 'list:delete' %}">Delete</a>
    <a href="{% url 'list:detail' %}">detail</a>
{% endblock %}
</body>
</html>